//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanMarOrderService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.integration.sanmar.com/", ConfigurationName="SanMarOrderService.SanMarPOServiceDelegate")]
    public interface SanMarPOServiceDelegate
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(submitPOResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(submitPO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getPreSubmitInfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getPreSubmitInfo))]
        System.Threading.Tasks.Task<SanMarOrderService.submitPOResponse1> submitPOAsync(SanMarOrderService.submitPORequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(submitPOResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(submitPO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getPreSubmitInfoResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getPreSubmitInfo))]
        System.Threading.Tasks.Task<SanMarOrderService.getPreSubmitInfoResponse1> getPreSubmitInfoAsync(SanMarOrderService.getPreSubmitInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class webServicePO
    {
        
        private string attentionField;
        
        private string internalMessageField;
        
        private string notesField;
        
        private string poNumField;
        
        private int poSenderIdField;
        
        private bool poSenderIdFieldSpecified;
        
        private string residenceField;
        
        private string departmentField;
        
        private string shipAddress1Field;
        
        private string shipAddress2Field;
        
        private string shipCityField;
        
        private string shipEmailField;
        
        private string shipMethodField;
        
        private string shipStateField;
        
        private string shipToField;
        
        private string shipZipField;
        
        private webServicePODetail[] webServicePoDetailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string attention
        {
            get
            {
                return this.attentionField;
            }
            set
            {
                this.attentionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string internalMessage
        {
            get
            {
                return this.internalMessageField;
            }
            set
            {
                this.internalMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string notes
        {
            get
            {
                return this.notesField;
            }
            set
            {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string poNum
        {
            get
            {
                return this.poNumField;
            }
            set
            {
                this.poNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int poSenderId
        {
            get
            {
                return this.poSenderIdField;
            }
            set
            {
                this.poSenderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poSenderIdSpecified
        {
            get
            {
                return this.poSenderIdFieldSpecified;
            }
            set
            {
                this.poSenderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string residence
        {
            get
            {
                return this.residenceField;
            }
            set
            {
                this.residenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string shipAddress1
        {
            get
            {
                return this.shipAddress1Field;
            }
            set
            {
                this.shipAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string shipAddress2
        {
            get
            {
                return this.shipAddress2Field;
            }
            set
            {
                this.shipAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string shipCity
        {
            get
            {
                return this.shipCityField;
            }
            set
            {
                this.shipCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string shipEmail
        {
            get
            {
                return this.shipEmailField;
            }
            set
            {
                this.shipEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string shipMethod
        {
            get
            {
                return this.shipMethodField;
            }
            set
            {
                this.shipMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string shipState
        {
            get
            {
                return this.shipStateField;
            }
            set
            {
                this.shipStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string shipTo
        {
            get
            {
                return this.shipToField;
            }
            set
            {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string shipZip
        {
            get
            {
                return this.shipZipField;
            }
            set
            {
                this.shipZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("webServicePoDetailList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public webServicePODetail[] webServicePoDetailList
        {
            get
            {
                return this.webServicePoDetailListField;
            }
            set
            {
                this.webServicePoDetailListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class webServicePODetail
    {
        
        private string colorField;
        
        private bool errorOccuredField;
        
        private bool errorOccuredFieldSpecified;
        
        private string inventoryKeyField;
        
        private string messageField;
        
        private int poIdField;
        
        private bool poIdFieldSpecified;
        
        private int quantityField;
        
        private bool quantityFieldSpecified;
        
        private string sizeField;
        
        private int sizeIndexField;
        
        private bool sizeIndexFieldSpecified;
        
        private string styleField;
        
        private int whseNoField;
        
        private bool whseNoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool errorOccured
        {
            get
            {
                return this.errorOccuredField;
            }
            set
            {
                this.errorOccuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorOccuredSpecified
        {
            get
            {
                return this.errorOccuredFieldSpecified;
            }
            set
            {
                this.errorOccuredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string inventoryKey
        {
            get
            {
                return this.inventoryKeyField;
            }
            set
            {
                this.inventoryKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int poId
        {
            get
            {
                return this.poIdField;
            }
            set
            {
                this.poIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poIdSpecified
        {
            get
            {
                return this.poIdFieldSpecified;
            }
            set
            {
                this.poIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int sizeIndex
        {
            get
            {
                return this.sizeIndexField;
            }
            set
            {
                this.sizeIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeIndexSpecified
        {
            get
            {
                return this.sizeIndexFieldSpecified;
            }
            set
            {
                this.sizeIndexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string style
        {
            get
            {
                return this.styleField;
            }
            set
            {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int whseNo
        {
            get
            {
                return this.whseNoField;
            }
            set
            {
                this.whseNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool whseNoSpecified
        {
            get
            {
                return this.whseNoFieldSpecified;
            }
            set
            {
                this.whseNoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class submitPOResponse
    {
        
        private responseBean returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseBean @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class responseBean
    {
        
        private bool errorOccurredField;
        
        private object[] listResponseField;
        
        private string messageField;
        
        private object responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool errorOccurred
        {
            get
            {
                return this.errorOccurredField;
            }
            set
            {
                this.errorOccurredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public object[] listResponse
        {
            get
            {
                return this.listResponseField;
            }
            set
            {
                this.listResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class submitPO
    {
        
        private webServicePO arg0Field;
        
        private webServiceUser arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public webServicePO arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public webServiceUser arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class webServiceUser
    {
        
        private string sanMarCustomerNumberField;
        
        private string sanMarUserNameField;
        
        private string sanMarUserPasswordField;
        
        private int senderIdField;
        
        private bool senderIdFieldSpecified;
        
        private string senderPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sanMarCustomerNumber
        {
            get
            {
                return this.sanMarCustomerNumberField;
            }
            set
            {
                this.sanMarCustomerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sanMarUserName
        {
            get
            {
                return this.sanMarUserNameField;
            }
            set
            {
                this.sanMarUserNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sanMarUserPassword
        {
            get
            {
                return this.sanMarUserPasswordField;
            }
            set
            {
                this.sanMarUserPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int senderId
        {
            get
            {
                return this.senderIdField;
            }
            set
            {
                this.senderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool senderIdSpecified
        {
            get
            {
                return this.senderIdFieldSpecified;
            }
            set
            {
                this.senderIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string senderPassword
        {
            get
            {
                return this.senderPasswordField;
            }
            set
            {
                this.senderPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class getPreSubmitInfoResponse
    {
        
        private responseBean returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public responseBean @return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.integration.sanmar.com/")]
    public partial class getPreSubmitInfo
    {
        
        private webServicePO arg0Field;
        
        private webServiceUser arg1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public webServicePO arg0
        {
            get
            {
                return this.arg0Field;
            }
            set
            {
                this.arg0Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public webServiceUser arg1
        {
            get
            {
                return this.arg1Field;
            }
            set
            {
                this.arg1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitPO", WrapperNamespace="http://webservice.integration.sanmar.com/", IsWrapped=true)]
    public partial class submitPORequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.integration.sanmar.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SanMarOrderService.webServicePO arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.integration.sanmar.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SanMarOrderService.webServiceUser arg1;
        
        public submitPORequest()
        {
        }
        
        public submitPORequest(SanMarOrderService.webServicePO arg0, SanMarOrderService.webServiceUser arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="submitPOResponse", WrapperNamespace="http://webservice.integration.sanmar.com/", IsWrapped=true)]
    public partial class submitPOResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.integration.sanmar.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SanMarOrderService.responseBean @return;
        
        public submitPOResponse1()
        {
        }
        
        public submitPOResponse1(SanMarOrderService.responseBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPreSubmitInfo", WrapperNamespace="http://webservice.integration.sanmar.com/", IsWrapped=true)]
    public partial class getPreSubmitInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.integration.sanmar.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SanMarOrderService.webServicePO arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.integration.sanmar.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SanMarOrderService.webServiceUser arg1;
        
        public getPreSubmitInfoRequest()
        {
        }
        
        public getPreSubmitInfoRequest(SanMarOrderService.webServicePO arg0, SanMarOrderService.webServiceUser arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPreSubmitInfoResponse", WrapperNamespace="http://webservice.integration.sanmar.com/", IsWrapped=true)]
    public partial class getPreSubmitInfoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.integration.sanmar.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SanMarOrderService.responseBean @return;
        
        public getPreSubmitInfoResponse1()
        {
        }
        
        public getPreSubmitInfoResponse1(SanMarOrderService.responseBean @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SanMarPOServiceDelegateChannel : SanMarOrderService.SanMarPOServiceDelegate, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SanMarPOServiceDelegateClient : System.ServiceModel.ClientBase<SanMarOrderService.SanMarPOServiceDelegate>, SanMarOrderService.SanMarPOServiceDelegate
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SanMarPOServiceDelegateClient() : 
                base(SanMarPOServiceDelegateClient.GetDefaultBinding(), SanMarPOServiceDelegateClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SanMarPOServiceImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanMarPOServiceDelegateClient(EndpointConfiguration endpointConfiguration) : 
                base(SanMarPOServiceDelegateClient.GetBindingForEndpoint(endpointConfiguration), SanMarPOServiceDelegateClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanMarPOServiceDelegateClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SanMarPOServiceDelegateClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanMarPOServiceDelegateClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SanMarPOServiceDelegateClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanMarPOServiceDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SanMarOrderService.submitPOResponse1> SanMarOrderService.SanMarPOServiceDelegate.submitPOAsync(SanMarOrderService.submitPORequest request)
        {
            return base.Channel.submitPOAsync(request);
        }
        
        public System.Threading.Tasks.Task<SanMarOrderService.submitPOResponse1> submitPOAsync(SanMarOrderService.webServicePO arg0, SanMarOrderService.webServiceUser arg1)
        {
            SanMarOrderService.submitPORequest inValue = new SanMarOrderService.submitPORequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SanMarOrderService.SanMarPOServiceDelegate)(this)).submitPOAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SanMarOrderService.getPreSubmitInfoResponse1> SanMarOrderService.SanMarPOServiceDelegate.getPreSubmitInfoAsync(SanMarOrderService.getPreSubmitInfoRequest request)
        {
            return base.Channel.getPreSubmitInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SanMarOrderService.getPreSubmitInfoResponse1> getPreSubmitInfoAsync(SanMarOrderService.webServicePO arg0, SanMarOrderService.webServiceUser arg1)
        {
            SanMarOrderService.getPreSubmitInfoRequest inValue = new SanMarOrderService.getPreSubmitInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SanMarOrderService.SanMarPOServiceDelegate)(this)).getPreSubmitInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SanMarPOServiceImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SanMarPOServiceImplPort))
            {
                // EDEV for testing only
                return new System.ServiceModel.EndpointAddress("https://edev-ws.sanmar.com:8080/SanMarWebService/SanMarPOServicePort");
                //return new System.ServiceModel.EndpointAddress("https://ws.sanmar.com:8080/SanMarWebService/SanMarPOServicePort");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SanMarPOServiceDelegateClient.GetBindingForEndpoint(EndpointConfiguration.SanMarPOServiceImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SanMarPOServiceDelegateClient.GetEndpointAddress(EndpointConfiguration.SanMarPOServiceImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            SanMarPOServiceImplPort,
        }
    }
}
